server:
  port: 9001
  
eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: api-gateway
    
zuul:
    ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
    

  