server:
  port: 9001
  
eureka:  instance:    hostname: localhost

spring:  application:    name: api-gateway
  cloud:    gateway:      routes:      - id: user-service
        uri:          lb://user-service
        predicates:        - Path=/user/**
      - id: email-service
        uri:
          lb://email-service
        predicates:
        - Path=/email/**
      - id: sector-service
        uri:
          lb://sector-service
        predicates:
        - Path=/admin/sectors/**
      - id: stockExchange-service
        uri:
          lb://stockExchange-service
        predicates:
        - Path=/stock-exchanges/**
      - id: IPO-service
        uri:
          lb://IPO-service
        predicates:
        - Path=/ipo/**
      - id: company-service
        uri:
          lb://company-service
        predicates:
        - Path=/companies/**


      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - content-type
            allowedMethods:
            - GET
            - POST             
        
